<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_libraries_info().
 */
function swiper_libraries_info() {
    $libraries['swiper'] = array(
        'name' => 'Swiper',
        'vendor url' => 'http://idangero.us/swiper/',
        'download url' => 'https://github.com/nolimits4web/Swiper/archive/v3.3.1.zip',
        'version arguments' => array(
            'file' => 'swiper.js',
            'pattern' => '/Swiper (\d+\.+\d+\.+\d)/',
            'lines' => 2,
        ),
        'files' => array(
            'js' => array(
                'swiper.js',
            ),
            'css' => array(
                'swiper.css',
            ),
        ),
    );

    return $libraries;
}

/**
 * Implements hook_requirements().
 */
function swiper_requirements($phase) {
    $requirements = array();

    if ($phase == 'runtime') {
        $t = get_t();
        $library = libraries_detect('swiper');

        if (empty($library['installed'])) {
            $requirements['swiper_plugin'] = array(
                'title' => $t('Swiper library'),
                'value' => $t('At least @a', array('@a' => '3.3.1')),
                'severity' => REQUIREMENT_ERROR,
                'description' =>
                    $t('You need to download the !swiper, extract @js_file and @css_file files from the archive and
               place them to the root of "swiper" directory in the %path directory on your server.',
                        array(
                            '!swiper' => l($t('Swiper library'), $library['download url']),
                            '%path' => 'sites/all/libraries',
                            '@js_file' => 'swiper.js',
                            '@css_file' => 'swiper.css',
                        )
                    ),
            );
        }
        elseif (version_compare($library['version'], '3.3.0', '>=')) {
            $requirements['swiper_plugin'] = array(
                'title' => $t('Swiper library'),
                'severity' => REQUIREMENT_OK,
                'value' => $library['version'],
            );
        }
        else {
            $requirements['swiper_plugin'] = array(
                'title' => $t('Swiper library'),
                'value' => $t('At least @a', array('@a' => '3.3.0')),
                'severity' => REQUIREMENT_ERROR,
                'description' =>
                    $t('You need to download a later version of the !swiper and replace the old version
                located in the %path directory on your server.',
                        array(
                            '!swiper' => l($t('Swiper library'), $library['download url']),
                            '%path' => $library['library path']
                        )
                    ),
            );
        }
    }

    return $requirements;
}

