<?php

/**
 * @file
 * Contains swiper.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function swiper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the swiper module.
    case 'help.page.swiper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Swiper slider libraries and API') . '</p>';
      return $output;

    default:
  }
}
